\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {Algorithmus}{\numberline {5.1}{\ignorespaces Alternierendes L\IeC {\"o}sen nach $g(k)$ und $E_i$\relax }}{23}{Algorithmus.caption.9}
\contentsline {Algorithmus}{\numberline {5.2}{\ignorespaces Erweitertes alternierendes L\IeC {\"o}sen nach $g(k)$ und $\qopname \relax o{ln}E_i$ mit Haupt- und Inneniterationen\relax }}{32}{Algorithmus.caption.10}
